spring:
  profiles:
    active: dev
    include: swagger
---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

zuul:
  routes:
    accounts:
      path: /accounts/**
      url: http://localhost:9001
